### ISSUE TITLE
matryoshka example breaks for

### ISSUE THREAD

**Issue by ghollisjr** [ukari/cl-generator#2]
I'm not sure if this is a real problem or not, but I found that the `matryoshka` generator example doesn't work with `for`, e.g.

`(defun* matryoshka (x)
    (yield (yield (yield x))))`

`(for (x (matryoshka 1)) (print x))`
`==> error about number of function arguments`

It does work with `iter-next`, so maybe `for` could be updated to handle nested `yield` statements?

**Comment by ukari** [comment]
Actually this usage of yield is a nontrivial situation which not just simply returns values like a number generator. For `matryoshka` function it needs input in every `funcall` of `iter-next`.

``` javascript
function* matryoshka(x) {
	return yield yield yield x;
}

a = matryoshka(1)
// Generator {  }

a.next()
// Object { value: 1, done: false }

a.next(2)
// Object { value: 2, done: false }

a.next(3)
// Object { value: 3, done: false }

a.next(4)
// Object { value: 4, done: true }
// now it's done
```

``` common lisp
(defun* matryoshka (x)
  (yield (yield (yield x))))

(defparameter a (matryoshka 1))

(funcall (iter-next a))
;; 1
(funcall (iter-next a) 2)
;; 2
(funcall (iter-next a) 3)
;; 3
(funcall (iter-next a) 4)
;; 4
(iter-next a)
;; nil
```

So it is impossible to infer and tell the `for` function what input needs to be provide to functions like `matryoshka`

**Comment by ghollisjr** [comment]
Ah that makes sense, I think this issue can just be closed
